version: '3'
services:
  web:
    build: .
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    ports:
      - "${APPLICATION_PORT}:80"
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    env_file:
      - .env

  dev:
    build: .
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    env_file:
      - .env
    command: bash