version: '3'
services:
  web:
    build: .
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    ports:
      - "${APPLICATION_PORT}:80"
    links:
      - maria
    environment:
      XDEBUG_CONFIG: remote_host=172.17.0.1
    env_file:
      - .env

  dev:
    build: .
    working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    env_file:
      - .env
    links:
      - maria
    command: bash

  maria:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_DATABASE_PORT}:3306"
    volumes:
      - /home/arun/mariadb/store/gds-tables:/var/lib/mysql
